import type { RecoveryIncident, Supplier, SupplierCommitment } from "@/lib/types";

export const DEMO_INCIDENT: RecoveryIncident = {
  id: "REC-260809-017",
  title: "Coolant pump supply interruption",
  cause: "Incumbent supplier reported an unplanned machining outage",
  plant: "Osaka Final Assembly",
  productionLine: "E-Drive Line 2",
  partNumber: "EP-220",
  partName: "Inverter coolant pump",
  incumbentSupplier: "Orion Thermal Systems",
  shortfall: 6_000,
  lineStopAt: "2026-08-11T09:30:00+09:00",
  estimatedDowntimeCost: 420_000,
  requirements: {
    quantity: 6_000,
    needBy: "2026-08-11",
    maxUnitPrice: 84,
    currency: "USD",
    requiredCertifications: ["IATF 16949", "ISO 9001"],
    allowedOrigins: ["JP", "MY", "DE", "VN", "CA"],
    approvedSubstituteParts: ["EP-220", "EP-220B"],
  },
};

export const DEMO_SUPPLIERS: Supplier[] = [
  {
    id: "sup-kanto",
    name: "Kanto Flow Systems",
    location: "Nagoya, Japan",
    countryCode: "JP",
    locale: "en-US",
    maskedPhone: "+81 •• •••• 4182",
    approvalTier: "Approved",
    historicalReliability: 96,
    lastVerified: "18 days ago",
    status: "ready",
  },
  {
    id: "sup-pacific",
    name: "Pacific Motion Works",
    location: "Penang, Malaysia",
    countryCode: "MY",
    locale: "en-US",
    maskedPhone: "+60 •• ••• 7731",
    approvalTier: "Approved",
    historicalReliability: 93,
    lastVerified: "31 days ago",
    status: "ready",
  },
  {
    id: "sup-rhein",
    name: "Rhein Auto Components",
    location: "Stuttgart, Germany",
    countryCode: "DE",
    locale: "en-US",
    maskedPhone: "+49 ••• •••• 902",
    approvalTier: "Approved",
    historicalReliability: 91,
    lastVerified: "12 days ago",
    status: "ready",
  },
  {
    id: "sup-delta",
    name: "Delta Fluidics",
    location: "Da Nang, Vietnam",
    countryCode: "VN",
    locale: "en-US",
    maskedPhone: "+84 •• •••• 6150",
    approvalTier: "Conditional",
    historicalReliability: 88,
    lastVerified: "44 days ago",
    status: "ready",
  },
  {
    id: "sup-summit",
    name: "Summit Industrial",
    location: "Ontario, Canada",
    countryCode: "CA",
    locale: "en-US",
    maskedPhone: "+1 ••• ••• 0844",
    approvalTier: "Approved",
    historicalReliability: 89,
    lastVerified: "27 days ago",
    status: "ready",
  },
];

export const DEMO_COMMITMENTS: Record<string, SupplierCommitment | null> = {
  "sup-kanto": {
    supplierId: "sup-kanto",
    availabilityStatus: "available",
    quantityAvailable: 6_000,
    earliestShipDate: "2026-08-10",
    unitPrice: 76.8,
    currency: "USD",
    moq: 2_000,
    originCountry: "JP",
    substitutePart: "EP-220",
    certifications: ["IATF 16949", "ISO 9001"],
    quoteValidUntil: "2026-08-10T17:00:00+09:00",
    respondentName: "Mika Sato",
    respondentTitle: "Sales Operations Director",
    authorityConfirmed: true,
    constraints: ["Air freight required for the first 2,000 units"],
    evidenceQuote: "I can commit six thousand EP-220 units, with the first shipment tomorrow.",
    confidence: 0.96,
    callDurationSeconds: 132,
    transcript: [
      { speaker: "agent", offsetSeconds: 4, text: "I’m calling for Northstar Mobility about approved part EP-220. I’m not placing an order. May I confirm your live capacity and delivery commitment?" },
      { speaker: "supplier", offsetSeconds: 19, text: "Yes. I’m Mika Sato, Sales Operations Director, and I’m authorized to confirm current allocation." },
      { speaker: "agent", offsetSeconds: 43, text: "Can you commit 6,000 units for shipment no later than August 11, under 84 US dollars per unit?" },
      { speaker: "supplier", offsetSeconds: 58, text: "I can commit six thousand EP-220 units, with the first shipment tomorrow. Price is 76 dollars and 80 cents. IATF and ISO certificates are current." },
      { speaker: "supplier", offsetSeconds: 102, text: "The quote is valid until 5 PM Japan time tomorrow. Two thousand need air freight; the balance can move by expedited road and air." },
    ],
  },
  "sup-pacific": {
    supplierId: "sup-pacific",
    availabilityStatus: "available",
    quantityAvailable: 8_000,
    earliestShipDate: "2026-08-11",
    unitPrice: 72.4,
    currency: "USD",
    moq: 4_000,
    originCountry: "MY",
    substitutePart: "EP-220B",
    certifications: ["IATF 16949", "ISO 9001"],
    quoteValidUntil: "2026-08-11T12:00:00+08:00",
    respondentName: "Daniel Lim",
    respondentTitle: "Regional Commercial Manager",
    authorityConfirmed: true,
    constraints: ["Uses approved EP-220B substitute", "Buyer must release forecast today"],
    evidenceQuote: "Eight thousand EP-220B units are reserved and can leave Penang on the eleventh.",
    confidence: 0.92,
    callDurationSeconds: 149,
    transcript: [
      { speaker: "agent", offsetSeconds: 3, text: "This is a capacity verification call for Northstar Mobility. No purchase will be made on this call." },
      { speaker: "supplier", offsetSeconds: 27, text: "Understood. I can confirm allocation as Regional Commercial Manager." },
      { speaker: "supplier", offsetSeconds: 61, text: "Eight thousand EP-220B units are reserved and can leave Penang on the eleventh, at 72 dollars and 40 cents." },
      { speaker: "supplier", offsetSeconds: 108, text: "Both certificates are valid. We need the forecast released today to keep the slot." },
    ],
  },
  "sup-rhein": {
    supplierId: "sup-rhein",
    availabilityStatus: "partial",
    quantityAvailable: 4_000,
    earliestShipDate: "2026-08-12",
    unitPrice: 79.2,
    currency: "USD",
    moq: 1_000,
    originCountry: "DE",
    substitutePart: "EP-220",
    certifications: ["IATF 16949", "ISO 9001"],
    quoteValidUntil: "2026-08-12T16:00:00+02:00",
    respondentName: "Anna Weber",
    respondentTitle: "Key Account Manager",
    authorityConfirmed: true,
    constraints: ["Only 4,000 units", "Ships one day after required date"],
    evidenceQuote: "Four thousand are possible, but the earliest departure is August twelfth.",
    confidence: 0.94,
    callDurationSeconds: 118,
    transcript: [
      { speaker: "agent", offsetSeconds: 5, text: "Can Rhein commit 6,000 EP-220 units by August 11?" },
      { speaker: "supplier", offsetSeconds: 36, text: "Four thousand are possible, but the earliest departure is August twelfth." },
      { speaker: "supplier", offsetSeconds: 81, text: "The price and certifications are within the requested terms." },
    ],
  },
  "sup-delta": {
    supplierId: "sup-delta",
    availabilityStatus: "available",
    quantityAvailable: 7_000,
    earliestShipDate: "2026-08-10",
    unitPrice: 68.5,
    currency: "USD",
    moq: 3_000,
    originCountry: "VN",
    substitutePart: "EP-220",
    certifications: ["ISO 9001"],
    quoteValidUntil: "2026-08-10T16:00:00+07:00",
    respondentName: "Minh Tran",
    respondentTitle: "Sales Manager",
    authorityConfirmed: true,
    constraints: ["IATF 16949 renewal audit is still pending"],
    evidenceQuote: "The IATF renewal is pending; I can only provide our current ISO certificate today.",
    confidence: 0.95,
    callDurationSeconds: 101,
    transcript: [
      { speaker: "agent", offsetSeconds: 4, text: "Please confirm quantity, ship date, price, origin, and both required certifications." },
      { speaker: "supplier", offsetSeconds: 33, text: "We can ship seven thousand tomorrow from Vietnam at 68 dollars and 50 cents." },
      { speaker: "supplier", offsetSeconds: 67, text: "The IATF renewal is pending; I can only provide our current ISO certificate today." },
    ],
  },
  "sup-summit": null,
};

export const DEMO_REVEAL_ORDER = ["sup-delta", "sup-kanto", "sup-rhein", "sup-pacific", "sup-summit"];
